name: oidc-poc
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
          - uses: jfrog/setup-jfrog-cli@v4
            env:
              JF_URL: https://rpesh2020.jfrog.io 
            with:
              oidc-provider-name: github-provider 
              oidc-audience: rpesh2020_1
